artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_data: 'C:/Users/Yashar/Slope-Stability-Prediction/data/slope_stability_dataset.csv'
  local_data_file: artifacts/data_ingestion/slope.csv

data_validation:
  root_dir: artifacts/data_validation
  source_data: 'artifacts//data_ingestion//slope.csv'
  STATUS_FILE: artifacts/data_validation/status.txt

data_preprocessing:
  root_dir: artifacts/data_preprocessing
  source_data: 'artifacts//data_ingestion//slope.csv'
  data_validation_status_file: artifacts/data_validation/status.txt
  X: artifacts/data_preprocessing/X.csv
  y: artifacts/data_preprocessing/y.csv
  train_test_split: artifacts/data_preprocessing/

model_trainer:
  root_dir: artifacts/model_trainer
  train_data_path: artifacts/data_preprocessing/X_train.csv
  test_data_path: artifacts/data_preprocessing/X_test.csv
  train_target_path: artifacts/data_preprocessing/y_train.csv
  test_target_path: artifacts/data_preprocessing/y_test.csv
  model_path: artifacts/model_trainer/model.joblib          
  rf_model_path: artifacts/model_trainer/rf_model.joblib    
  xgb_model_path: artifacts/model_trainer/xgb_model.joblib  
  metrics_path: artifacts/model_trainer/metrics.json

prediction:
  root_dir: artifacts/prediction
  X_path: artifacts/data_preprocessing/X.csv
  y_path: artifacts/data_preprocessing/y.csv          
  scaler_path: artifacts/data_preprocessing/scaler.joblib
  model_path: artifacts/model_trainer/model.joblib
  output_path: artifacts/prediction/predictions.csv
 